services:
  secure-invoke:
    image: ${SECURE_INVOKE_IMAGE:-${REGISTRY:-ispirt.azurecr.io/depa-inferencing/tools}/secure_invoke:${TAG}}
    network_mode: "host"
    container_name: secure_invoke_container
    volumes:
      - ${HOST_REQUESTS_DIR}:/requests  # Inference requests file dir - Send thru secure script argument or set env variable
      - ${HOST_CERTS_DIR}:/certs # Certificates dir - Send thru secure script argument or set env variable
    environment:
      KMS_HOST: ${KMS_HOST}
      BUYER_HOST: ${BUYER_HOST}
      OPERATION: ${OPERATION:-rest_invoke}
      TARGET_SERVICE: ${TARGET_SERVICE:-bfe}
      REQUEST_PATH: ${REQUEST_PATH:-requests/get_bids_request.json} # Inference requests file name
      RETRIES: ${RETRIES:-1}
      INSECURE: $(INSECURE}
      HEADERS: $(HEADERS}
      CLIENT_KEY: /certs/${CLIENT_KEY}
      CLIENT_CERT: /certs/${CLIENT_CERT}
      CA_CERT: /certs/${CA_CERT}
      ENABLE_VERBOSE: "${ENABLE_VERBOSE:-false}" # Controls verbose output
