# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secure_invoke_envelope.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csecure_invoke_envelope.proto\x12\'privacy_sandbox.bidding_auction_servers\"<\n\x0eGetBidsRequest\x12\x1a\n\x12request_ciphertext\x18\x01 \x01(\x0c\x12\x0e\n\x06key_id\x18\x02 \x01(\t\".\n\x0fGetBidsResponse\x12\x1b\n\x13response_ciphertext\x18\x01 \x01(\x0c\x32\x8f\x01\n\rBuyerFrontEnd\x12~\n\x07GetBids\x12\x37.privacy_sandbox.bidding_auction_servers.GetBidsRequest\x1a\x38.privacy_sandbox.bidding_auction_servers.GetBidsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secure_invoke_envelope_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBIDSREQUEST']._serialized_start=73
  _globals['_GETBIDSREQUEST']._serialized_end=133
  _globals['_GETBIDSRESPONSE']._serialized_start=135
  _globals['_GETBIDSRESPONSE']._serialized_end=181
  _globals['_BUYERFRONTEND']._serialized_start=184
  _globals['_BUYERFRONTEND']._serialized_end=327
# @@protoc_insertion_point(module_scope)
