# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import secure_invoke_envelope_pb2 as secure__invoke__envelope__pb2


class BuyerFrontEndStub(object):
    """Buyer's FrontEnd service (subset).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBids = channel.unary_unary(
                '/privacy_sandbox.bidding_auction_servers.BuyerFrontEnd/GetBids',
                request_serializer=secure__invoke__envelope__pb2.GetBidsRequest.SerializeToString,
                response_deserializer=secure__invoke__envelope__pb2.GetBidsResponse.FromString,
                )


class BuyerFrontEndServicer(object):
    """Buyer's FrontEnd service (subset).
    """

    def GetBids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerFrontEndServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBids': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBids,
                    request_deserializer=secure__invoke__envelope__pb2.GetBidsRequest.FromString,
                    response_serializer=secure__invoke__envelope__pb2.GetBidsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privacy_sandbox.bidding_auction_servers.BuyerFrontEnd', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerFrontEnd(object):
    """Buyer's FrontEnd service (subset).
    """

    @staticmethod
    def GetBids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/privacy_sandbox.bidding_auction_servers.BuyerFrontEnd/GetBids',
            secure__invoke__envelope__pb2.GetBidsRequest.SerializeToString,
            secure__invoke__envelope__pb2.GetBidsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
