name: Cleanup Azure Deployments

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  deploy-test-cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AKS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AKS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AKS_SUBSCRIPTION_ID }}

      - name: Terraform destroy (always cleanup)
        if: always()
        run: |
            az group delete --name tf-demo-offer-inc-rg --yes