name: Test Azure Deployment

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  deploy-test-cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AKS_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AKS_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_AKS_SUBSCRIPTION_ID }}

      - name: Update demo environment
        env: 
          AZURE_AKS_SUBSCRIPTION_ID: ${{ secrets.AZURE_AKS_SUBSCRIPTION_ID }}
          AZURE_AKS_TENANT_ID: ${{ secrets.AZURE_AKS_TENANT_ID }}
        run: |
          sed -i 's|<your_subscription_id>|'"$AZURE_AKS_SUBSCRIPTION_ID"'|g' ./deployment-scripts/azure/offer-service/environment/demo/terraform/offer.tf
          sed -i 's|<your_tenant_id>|'"$AZURE_AKS_TENANT_ID"'|g' ./deployment-scripts/azure/offer-service/environment/demo/terraform/offer.tf

      - name: Terraform init
        working-directory: ./deployment-scripts/azure/offer-service/environment/demo/terraform
        run: terraform init

      - name: Terraform apply
        working-directory: ./deployment-scripts/azure/offer-service/environment/demo/terraform
        env: 
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AKS_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_AKS_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AKS_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform apply -auto-approve

      - name: Generate data and UDF
        working-directory: ./tools/key-value-service
        run: |
          mkdir ./tmp
          ./data_cli.sh format_delta ./tools/key-value-service/data.csv ./tmp/delta_0000000000000001
          ./udf_delta_file_generator.sh ./tmp ./udf.js

      - name: Upload data and UDF
        run: |
          az storage file upload \
            --account-name tfdemooffincstorage \
            --share-name fslogix \
            --path deltas \
            --source ./tmp \
            --auth-mode login

      - name: Find IP address of offer frontend load balancer
        run: |
          az aks get-credentials --resource-group tf-demo-offer-inc-rg --name tf-demo-offer-inc-aks --overwrite-existing
          OFE_IP=$(kubectl get svc ofe-lb -n default -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
          echo "OFE_IP=$OFE_IP" >> $GITHUB_ENV

      - name: Run secure invoke
        env:
          KMS_URL: "https://depa-inferencing-kms.centralindia.cloudapp.azure.com"
        working-directory: ./tools/secure-invoke
        run: |
          sed -i 's|/home/azureuser|/home/runner|g' ./.env
          sed -i 's|<KMS_HOST>|'"$KMS_URL"'|g' ./.env
          sed -i 's|<hostname>|'"$OFE_IP"'|g' ./.env
          sed -i '/CA_CERT/d' ./.env
          sed -i '/CLIENT_CERT/d' ./.env
          sed -i '/CLIENT_KEY/d' ./.env
          ./secure_invoke_test.sh

      - name: Terraform destroy (always cleanup)
        if: always()
        working-directory: ./deployment-scripts/azure/offer-service/environment/demo/terraform
        env: 
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AKS_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_AKS_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_AKS_TENANT_ID }}
          ARM_USE_OIDC: true
        run: terraform destroy -auto-approve
