name: Update KMS policy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      bidding-auction-version:
        description: 'DEPA Inferencing Release Version for Bidding and Auction Services'
        required: true
        type: string
        default: '4.8.0.0'
      kv-services-version:
        description: 'DEPA Inferencing Release Version for KV Services'
        required: true
        type: string
        default: '1.2.0.0'

jobs:
  azure-login:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Azure CLI Confcom extension
        run: |
          az extension add --name confcom

      - name: Install CCF client Python package
        run: |
          pip install ccf-client==6.0.10

      - name: Generate CCE policies for services
        run: |
          # Generate CCE policy for KV service
          KV_POLICY=$(az confcom acipolicygen -a policies/kv.json --print-policy | base64 --decode | sha256sum)
          
          # Generate CCE policy for OFE service
          OFE_POLICY=$(az confcom acipolicygen -a policies/ofe.json --print-policy | base64 --decode | sha256sum)
          
          # Generate CCE policy for offer service
          OFFER_POLICY=$(az confcom acipolicygen -a policies/offer.json --print-policy | base64 --decode | sha256sum)
          
          echo "CCE policies generated for all services"

      - name: Generate key release policy JSON
        run: |
          # Extract just the hash values (remove the filename part from sha256sum output)
          KV_HASH=$(echo "$KV_POLICY" | cut -d' ' -f1)
          OFE_HASH=$(echo "$OFE_POLICY" | cut -d' ' -f1)
          OFFER_HASH=$(echo "$OFFER_POLICY" | cut -d' ' -f1)
          
          # Generate the JSON structure
          cat > key_release_policy.json << EOF
          {
            "actions": [
              {
                "name": "set_key_release_policy",
                "args": {
                  "service": "offer-services",
                  "type": "add",
                  "claims": {
                    "x-ms-sevsnpvm-hostdata": [
                      "$KV_HASH",
                      "$OFE_HASH",
                      "$OFFER_HASH"
                    ]
                  }
                }
              }
            ]
          }
          EOF
          
          echo "Key release policy JSON generated: key_release_policy.json"
          cat key_release_policy.json
